insert into "cities" ("id", "province_id", "name") values (1, 1, 'Kabupaten Aceh Selatan');
insert into "cities" ("id", "province_id", "name") values (2, 1, 'Kabupaten Aceh Tenggara');
insert into "cities" ("id", "province_id", "name") values (3, 1, 'Kabupaten Aceh Timur');
insert into "cities" ("id", "province_id", "name") values (4, 1, 'Kabupaten Aceh Tengah');
insert into "cities" ("id", "province_id", "name") values (5, 1, 'Kabupaten Aceh Barat');
insert into "cities" ("id", "province_id", "name") values (6, 1, 'Kabupaten Aceh Besar');
insert into "cities" ("id", "province_id", "name") values (7, 1, 'Kabupaten Pidie');
insert into "cities" ("id", "province_id", "name") values (8, 1, 'Kabupaten Aceh Utara');
insert into "cities" ("id", "province_id", "name") values (9, 1, 'Kabupaten Simeulue');
insert into "cities" ("id", "province_id", "name") values (10, 1, 'Kabupaten Aceh Singkil');
insert into "cities" ("id", "province_id", "name") values (11, 1, 'Kabupaten Bireuen');
insert into "cities" ("id", "province_id", "name") values (12, 1, 'Kabupaten Aceh Barat Daya');
insert into "cities" ("id", "province_id", "name") values (13, 1, 'Kabupaten Gayo Lues');
insert into "cities" ("id", "province_id", "name") values (14, 1, 'Kabupaten Aceh Jaya');
insert into "cities" ("id", "province_id", "name") values (15, 1, 'Kabupaten Nagan Raya');
insert into "cities" ("id", "province_id", "name") values (16, 1, 'Kabupaten Aceh Tamiang');
insert into "cities" ("id", "province_id", "name") values (17, 1, 'Kabupaten Bener Meriah');
insert into "cities" ("id", "province_id", "name") values (18, 1, 'Kabupaten Pidie Jaya');
insert into "cities" ("id", "province_id", "name") values (19, 1, 'Kota Banda Aceh');
insert into "cities" ("id", "province_id", "name") values (20, 1, 'Kota Sabang');
insert into "cities" ("id", "province_id", "name") values (21, 1, 'Kota Lhokseumawe');
insert into "cities" ("id", "province_id", "name") values (22, 1, 'Kota Langsa');
insert into "cities" ("id", "province_id", "name") values (23, 1, 'Kota Subulussalam');
insert into "cities" ("id", "province_id", "name") values (24, 2, 'Kabupaten Tapanuli Tengah');
insert into "cities" ("id", "province_id", "name") values (25, 2, 'Kabupaten Tapanuli Utara');
insert into "cities" ("id", "province_id", "name") values (26, 2, 'Kabupaten Tapanuli Selatan');
insert into "cities" ("id", "province_id", "name") values (27, 2, 'Kabupaten Nias');
insert into "cities" ("id", "province_id", "name") values (28, 2, 'Kabupaten Langkat');
insert into "cities" ("id", "province_id", "name") values (29, 2, 'Kabupaten Karo');
insert into "cities" ("id", "province_id", "name") values (30, 2, 'Kabupaten Deli Serdang');
insert into "cities" ("id", "province_id", "name") values (31, 2, 'Kabupaten Simalungun');
insert into "cities" ("id", "province_id", "name") values (32, 2, 'Kabupaten Asahan');
insert into "cities" ("id", "province_id", "name") values (33, 2, 'Kabupaten Labuhanbatu');
insert into "cities" ("id", "province_id", "name") values (34, 2, 'Kabupaten Dairi');
insert into "cities" ("id", "province_id", "name") values (35, 2, 'Kabupaten Toba');
insert into "cities" ("id", "province_id", "name") values (36, 2, 'Kabupaten Mandailing Natal');
insert into "cities" ("id", "province_id", "name") values (37, 2, 'Kabupaten Nias Selatan');
insert into "cities" ("id", "province_id", "name") values (38, 2, 'Kabupaten Pakpak Bharat');
insert into "cities" ("id", "province_id", "name") values (39, 2, 'Kabupaten Humbang Hasundutan');
insert into "cities" ("id", "province_id", "name") values (40, 2, 'Kabupaten Samosir');
insert into "cities" ("id", "province_id", "name") values (41, 2, 'Kabupaten Serdang Bedagai');
insert into "cities" ("id", "province_id", "name") values (42, 2, 'Kabupaten Batu Bara');
insert into "cities" ("id", "province_id", "name") values (43, 2, 'Kabupaten Padang Lawas Utara');
insert into "cities" ("id", "province_id", "name") values (44, 2, 'Kabupaten Padang Lawas');
insert into "cities" ("id", "province_id", "name") values (45, 2, 'Kabupaten Labuhanbatu Selatan');
insert into "cities" ("id", "province_id", "name") values (46, 2, 'Kabupaten Labuhanbatu Utara');
insert into "cities" ("id", "province_id", "name") values (47, 2, 'Kabupaten Nias Utara');
insert into "cities" ("id", "province_id", "name") values (48, 2, 'Kabupaten Nias Barat');
insert into "cities" ("id", "province_id", "name") values (49, 2, 'Kota Medan');
insert into "cities" ("id", "province_id", "name") values (50, 2, 'Kota Pematangsiantar');
insert into "cities" ("id", "province_id", "name") values (51, 2, 'Kota Sibolga');
insert into "cities" ("id", "province_id", "name") values (52, 2, 'Kota Tanjung Balai');
insert into "cities" ("id", "province_id", "name") values (53, 2, 'Kota Binjai');
insert into "cities" ("id", "province_id", "name") values (54, 2, 'Kota Tebing Tinggi');
insert into "cities" ("id", "province_id", "name") values (55, 2, 'Kota Padangsidimpuan');
insert into "cities" ("id", "province_id", "name") values (56, 2, 'Kota Gunungsitoli');
insert into "cities" ("id", "province_id", "name") values (57, 3, 'Kabupaten Pesisir Selatan');
insert into "cities" ("id", "province_id", "name") values (58, 3, 'Kabupaten Solok');
insert into "cities" ("id", "province_id", "name") values (59, 3, 'Kabupaten Sijunjung');
insert into "cities" ("id", "province_id", "name") values (60, 3, 'Kabupaten Tanah Datar');
insert into "cities" ("id", "province_id", "name") values (61, 3, 'Kabupaten Padang Pariaman');
insert into "cities" ("id", "province_id", "name") values (62, 3, 'Kabupaten Agam');
insert into "cities" ("id", "province_id", "name") values (63, 3, 'Kabupaten Lima Puluh Kota');
insert into "cities" ("id", "province_id", "name") values (64, 3, 'Kabupaten Pasaman');
insert into "cities" ("id", "province_id", "name") values (65, 3, 'Kabupaten Kepulauan Mentawai');
insert into "cities" ("id", "province_id", "name") values (66, 3, 'Kabupaten Dharmasraya');
insert into "cities" ("id", "province_id", "name") values (67, 3, 'Kabupaten Solok Selatan');
insert into "cities" ("id", "province_id", "name") values (68, 3, 'Kabupaten Pasaman Barat');
insert into "cities" ("id", "province_id", "name") values (69, 3, 'Kota Padang');
insert into "cities" ("id", "province_id", "name") values (70, 3, 'Kota Solok');
insert into "cities" ("id", "province_id", "name") values (71, 3, 'Kota Sawahlunto');
insert into "cities" ("id", "province_id", "name") values (72, 3, 'Kota Padang Panjang');
insert into "cities" ("id", "province_id", "name") values (73, 3, 'Kota Bukittinggi');
insert into "cities" ("id", "province_id", "name") values (74, 3, 'Kota Payakumbuh');
insert into "cities" ("id", "province_id", "name") values (75, 3, 'Kota Pariaman');
insert into "cities" ("id", "province_id", "name") values (76, 4, 'Kabupaten Kampar');
insert into "cities" ("id", "province_id", "name") values (77, 4, 'Kabupaten Indragiri Hulu');
insert into "cities" ("id", "province_id", "name") values (78, 4, 'Kabupaten Bengkalis');
insert into "cities" ("id", "province_id", "name") values (79, 4, 'Kabupaten Indragiri Hilir');
insert into "cities" ("id", "province_id", "name") values (80, 4, 'Kabupaten Pelalawan');
insert into "cities" ("id", "province_id", "name") values (81, 4, 'Kabupaten Rokan Hulu');
insert into "cities" ("id", "province_id", "name") values (82, 4, 'Kabupaten Rokan Hilir');
insert into "cities" ("id", "province_id", "name") values (83, 4, 'Kabupaten Siak');
insert into "cities" ("id", "province_id", "name") values (84, 4, 'Kabupaten Kuantan Singingi');
insert into "cities" ("id", "province_id", "name") values (85, 4, 'Kabupaten Kepulauan Meranti');
insert into "cities" ("id", "province_id", "name") values (86, 4, 'Kota Pekanbaru');
insert into "cities" ("id", "province_id", "name") values (87, 4, 'Kota Dumai');
insert into "cities" ("id", "province_id", "name") values (88, 5, 'Kabupaten Kerinci');
insert into "cities" ("id", "province_id", "name") values (89, 5, 'Kabupaten Merangin');
insert into "cities" ("id", "province_id", "name") values (90, 5, 'Kabupaten Sarolangun');
insert into "cities" ("id", "province_id", "name") values (91, 5, 'Kabupaten Batanghari');
insert into "cities" ("id", "province_id", "name") values (92, 5, 'Kabupaten Muaro Jambi');
insert into "cities" ("id", "province_id", "name") values (93, 5, 'Kabupaten Tanjung Jabung Barat');
insert into "cities" ("id", "province_id", "name") values (94, 5, 'Kabupaten Tanjung Jabung Timur');
insert into "cities" ("id", "province_id", "name") values (95, 5, 'Kabupaten Bungo');
insert into "cities" ("id", "province_id", "name") values (96, 5, 'Kabupaten Tebo');
insert into "cities" ("id", "province_id", "name") values (97, 5, 'Kota Jambi');
insert into "cities" ("id", "province_id", "name") values (98, 5, 'Kota Sungai Penuh');
insert into "cities" ("id", "province_id", "name") values (99, 6, 'Kabupaten Ogan Komering Ulu');
insert into "cities" ("id", "province_id", "name") values (100, 6, 'Kabupaten Ogan Komering Ilir');
insert into "cities" ("id", "province_id", "name") values (101, 6, 'Kabupaten Muara Enim');
insert into "cities" ("id", "province_id", "name") values (102, 6, 'Kabupaten Lahat');
insert into "cities" ("id", "province_id", "name") values (103, 6, 'Kabupaten Musi Rawas');
insert into "cities" ("id", "province_id", "name") values (104, 6, 'Kabupaten Musi Banyuasin');
insert into "cities" ("id", "province_id", "name") values (105, 6, 'Kabupaten Banyuasin');
insert into "cities" ("id", "province_id", "name") values (106, 6, 'Kabupaten Ogan Komering Ulu Timur');
insert into "cities" ("id", "province_id", "name") values (107, 6, 'Kabupaten Ogan Komering Ulu Selatan');
insert into "cities" ("id", "province_id", "name") values (108, 6, 'Kabupaten Ogan Ilir');
insert into "cities" ("id", "province_id", "name") values (109, 6, 'Kabupaten Empat Lawang');
insert into "cities" ("id", "province_id", "name") values (110, 6, 'Kabupaten Penukal Abab Lematang Ilir');
insert into "cities" ("id", "province_id", "name") values (111, 6, 'Kabupaten Musi Rawas Utara');
insert into "cities" ("id", "province_id", "name") values (112, 6, 'Kota Palembang');
insert into "cities" ("id", "province_id", "name") values (113, 6, 'Kota Pagar Alam');
insert into "cities" ("id", "province_id", "name") values (114, 6, 'Kota Lubuk Linggau');
insert into "cities" ("id", "province_id", "name") values (115, 6, 'Kota Prabumulih');
insert into "cities" ("id", "province_id", "name") values (116, 7, 'Kabupaten Bengkulu Selatan');
insert into "cities" ("id", "province_id", "name") values (117, 7, 'Kabupaten Rejang Lebong');
insert into "cities" ("id", "province_id", "name") values (118, 7, 'Kabupaten Bengkulu Utara');
insert into "cities" ("id", "province_id", "name") values (119, 7, 'Kabupaten Kaur');
insert into "cities" ("id", "province_id", "name") values (120, 7, 'Kabupaten Seluma');
insert into "cities" ("id", "province_id", "name") values (121, 7, 'Kabupaten Muko Muko');
insert into "cities" ("id", "province_id", "name") values (122, 7, 'Kabupaten Lebong');
insert into "cities" ("id", "province_id", "name") values (123, 7, 'Kabupaten Kepahiang');
insert into "cities" ("id", "province_id", "name") values (124, 7, 'Kabupaten Bengkulu Tengah');
insert into "cities" ("id", "province_id", "name") values (125, 7, 'Kota Bengkulu');
insert into "cities" ("id", "province_id", "name") values (126, 8, 'Kabupaten Lampung Selatan');
insert into "cities" ("id", "province_id", "name") values (127, 8, 'Kabupaten Lampung Tengah');
insert into "cities" ("id", "province_id", "name") values (128, 8, 'Kabupaten Lampung Utara');
insert into "cities" ("id", "province_id", "name") values (129, 8, 'Kabupaten Lampung Barat');
insert into "cities" ("id", "province_id", "name") values (130, 8, 'Kabupaten Tulang Bawang');
insert into "cities" ("id", "province_id", "name") values (131, 8, 'Kabupaten Tanggamus');
insert into "cities" ("id", "province_id", "name") values (132, 8, 'Kabupaten Lampung Timur');
insert into "cities" ("id", "province_id", "name") values (133, 8, 'Kabupaten Way Kanan');
insert into "cities" ("id", "province_id", "name") values (134, 8, 'Kabupaten Pesawaran');
insert into "cities" ("id", "province_id", "name") values (135, 8, 'Kabupaten Pringsewu');
insert into "cities" ("id", "province_id", "name") values (136, 8, 'Kabupaten Mesuji');
insert into "cities" ("id", "province_id", "name") values (137, 8, 'Kabupaten Tulang Bawang Barat');
insert into "cities" ("id", "province_id", "name") values (138, 8, 'Kabupaten Pesisir Barat');
insert into "cities" ("id", "province_id", "name") values (139, 8, 'Kota Bandar Lampung');
insert into "cities" ("id", "province_id", "name") values (140, 8, 'Kota Metro');
insert into "cities" ("id", "province_id", "name") values (141, 9, 'Kabupaten Bangka');
insert into "cities" ("id", "province_id", "name") values (142, 9, 'Kabupaten Belitung');
insert into "cities" ("id", "province_id", "name") values (143, 9, 'Kabupaten Bangka Selatan');
insert into "cities" ("id", "province_id", "name") values (144, 9, 'Kabupaten Bangka Tengah');
insert into "cities" ("id", "province_id", "name") values (145, 9, 'Kabupaten Bangka Barat');
insert into "cities" ("id", "province_id", "name") values (146, 9, 'Kabupaten Belitung Timur');
insert into "cities" ("id", "province_id", "name") values (147, 9, 'Kota Pangkal Pinang');
insert into "cities" ("id", "province_id", "name") values (148, 10, 'Kabupaten Bintan');
insert into "cities" ("id", "province_id", "name") values (149, 10, 'Kabupaten Karimun');
insert into "cities" ("id", "province_id", "name") values (150, 10, 'Kabupaten Natuna');
insert into "cities" ("id", "province_id", "name") values (151, 10, 'Kabupaten Lingga');
insert into "cities" ("id", "province_id", "name") values (152, 10, 'Kabupaten Kepulauan Anambas');
insert into "cities" ("id", "province_id", "name") values (153, 10, 'Kota Batam');
insert into "cities" ("id", "province_id", "name") values (154, 10, 'Kota Tanjung Pinang');
insert into "cities" ("id", "province_id", "name") values (155, 11, 'Kabupaten Kepulauan Seribu');
insert into "cities" ("id", "province_id", "name") values (156, 11, 'Kota Jakarta Pusat');
insert into "cities" ("id", "province_id", "name") values (157, 11, 'Kota Jakarta Utara');
insert into "cities" ("id", "province_id", "name") values (158, 11, 'Kota Jakarta Barat');
insert into "cities" ("id", "province_id", "name") values (159, 11, 'Kota Jakarta Selatan');
insert into "cities" ("id", "province_id", "name") values (160, 11, 'Kota Jakarta Timur');
insert into "cities" ("id", "province_id", "name") values (161, 12, 'Kabupaten Bogor');
insert into "cities" ("id", "province_id", "name") values (162, 12, 'Kabupaten Sukabumi');
insert into "cities" ("id", "province_id", "name") values (163, 12, 'Kabupaten Cianjur');
insert into "cities" ("id", "province_id", "name") values (164, 12, 'Kabupaten Bandung');
insert into "cities" ("id", "province_id", "name") values (165, 12, 'Kabupaten Garut');
insert into "cities" ("id", "province_id", "name") values (166, 12, 'Kabupaten Tasikmalaya');
insert into "cities" ("id", "province_id", "name") values (167, 12, 'Kabupaten Ciamis');
insert into "cities" ("id", "province_id", "name") values (168, 12, 'Kabupaten Kuningan');
insert into "cities" ("id", "province_id", "name") values (169, 12, 'Kabupaten Cirebon');
insert into "cities" ("id", "province_id", "name") values (170, 12, 'Kabupaten Majalengka');
insert into "cities" ("id", "province_id", "name") values (171, 12, 'Kabupaten Sumedang');
insert into "cities" ("id", "province_id", "name") values (172, 12, 'Kabupaten Indramayu');
insert into "cities" ("id", "province_id", "name") values (173, 12, 'Kabupaten Subang');
insert into "cities" ("id", "province_id", "name") values (174, 12, 'Kabupaten Purwakarta');
insert into "cities" ("id", "province_id", "name") values (175, 12, 'Kabupaten Karawang');
insert into "cities" ("id", "province_id", "name") values (176, 12, 'Kabupaten Bekasi');
insert into "cities" ("id", "province_id", "name") values (177, 12, 'Kabupaten Bandung Barat');
insert into "cities" ("id", "province_id", "name") values (178, 12, 'Kabupaten Pangandaran');
insert into "cities" ("id", "province_id", "name") values (179, 12, 'Kota Bogor');
insert into "cities" ("id", "province_id", "name") values (180, 12, 'Kota Sukabumi');
insert into "cities" ("id", "province_id", "name") values (181, 12, 'Kota Bandung');
insert into "cities" ("id", "province_id", "name") values (182, 12, 'Kota Cirebon');
insert into "cities" ("id", "province_id", "name") values (183, 12, 'Kota Bekasi');
insert into "cities" ("id", "province_id", "name") values (184, 12, 'Kota Depok');
insert into "cities" ("id", "province_id", "name") values (185, 12, 'Kota Cimahi');
insert into "cities" ("id", "province_id", "name") values (186, 12, 'Kota Tasikmalaya');
insert into "cities" ("id", "province_id", "name") values (187, 12, 'Kota Banjar');
insert into "cities" ("id", "province_id", "name") values (188, 13, 'Kabupaten Cilacap');
insert into "cities" ("id", "province_id", "name") values (189, 13, 'Kabupaten Banyumas');
insert into "cities" ("id", "province_id", "name") values (190, 13, 'Kabupaten Purbalingga');
insert into "cities" ("id", "province_id", "name") values (191, 13, 'Kabupaten Banjarnegara');
insert into "cities" ("id", "province_id", "name") values (192, 13, 'Kabupaten Kebumen');
insert into "cities" ("id", "province_id", "name") values (193, 13, 'Kabupaten Purworejo');
insert into "cities" ("id", "province_id", "name") values (194, 13, 'Kabupaten Wonosobo');
insert into "cities" ("id", "province_id", "name") values (195, 13, 'Kabupaten Magelang');
insert into "cities" ("id", "province_id", "name") values (196, 13, 'Kabupaten Boyolali');
insert into "cities" ("id", "province_id", "name") values (197, 13, 'Kabupaten Klaten');
insert into "cities" ("id", "province_id", "name") values (198, 13, 'Kabupaten Sukoharjo');
insert into "cities" ("id", "province_id", "name") values (199, 13, 'Kabupaten Wonogiri');
insert into "cities" ("id", "province_id", "name") values (200, 13, 'Kabupaten Karanganyar');
insert into "cities" ("id", "province_id", "name") values (201, 13, 'Kabupaten Sragen');
insert into "cities" ("id", "province_id", "name") values (202, 13, 'Kabupaten Grobogan');
insert into "cities" ("id", "province_id", "name") values (203, 13, 'Kabupaten Blora');
insert into "cities" ("id", "province_id", "name") values (204, 13, 'Kabupaten Rembang');
insert into "cities" ("id", "province_id", "name") values (205, 13, 'Kabupaten Pati');
insert into "cities" ("id", "province_id", "name") values (206, 13, 'Kabupaten Kudus');
insert into "cities" ("id", "province_id", "name") values (207, 13, 'Kabupaten Jepara');
insert into "cities" ("id", "province_id", "name") values (208, 13, 'Kabupaten Demak');
insert into "cities" ("id", "province_id", "name") values (209, 13, 'Kabupaten Semarang');
insert into "cities" ("id", "province_id", "name") values (210, 13, 'Kabupaten Temanggung');
insert into "cities" ("id", "province_id", "name") values (211, 13, 'Kabupaten Kendal');
insert into "cities" ("id", "province_id", "name") values (212, 13, 'Kabupaten Batang');
insert into "cities" ("id", "province_id", "name") values (213, 13, 'Kabupaten Pekalongan');
insert into "cities" ("id", "province_id", "name") values (214, 13, 'Kabupaten Pemalang');
insert into "cities" ("id", "province_id", "name") values (215, 13, 'Kabupaten Tegal');
insert into "cities" ("id", "province_id", "name") values (216, 13, 'Kabupaten Brebes');
insert into "cities" ("id", "province_id", "name") values (217, 13, 'Kota Magelang');
insert into "cities" ("id", "province_id", "name") values (218, 13, 'Kota Surakarta');
insert into "cities" ("id", "province_id", "name") values (219, 13, 'Kota Salatiga');
insert into "cities" ("id", "province_id", "name") values (220, 13, 'Kota Semarang');
insert into "cities" ("id", "province_id", "name") values (221, 13, 'Kota Pekalongan');
insert into "cities" ("id", "province_id", "name") values (222, 13, 'Kota Tegal');
insert into "cities" ("id", "province_id", "name") values (223, 14, 'Kabupaten Kulon Progo');
insert into "cities" ("id", "province_id", "name") values (224, 14, 'Kabupaten Bantul');
insert into "cities" ("id", "province_id", "name") values (225, 14, 'Kabupaten Gunungkidul');
insert into "cities" ("id", "province_id", "name") values (226, 14, 'Kabupaten Sleman');
insert into "cities" ("id", "province_id", "name") values (227, 14, 'Kota Yogyakarta');
insert into "cities" ("id", "province_id", "name") values (228, 15, 'Kabupaten Pacitan');
insert into "cities" ("id", "province_id", "name") values (229, 15, 'Kabupaten Ponorogo');
insert into "cities" ("id", "province_id", "name") values (230, 15, 'Kabupaten Trenggalek');
insert into "cities" ("id", "province_id", "name") values (231, 15, 'Kabupaten Tulungagung');
insert into "cities" ("id", "province_id", "name") values (232, 15, 'Kabupaten Blitar');
insert into "cities" ("id", "province_id", "name") values (233, 15, 'Kabupaten Kediri');
insert into "cities" ("id", "province_id", "name") values (234, 15, 'Kabupaten Malang');
insert into "cities" ("id", "province_id", "name") values (235, 15, 'Kabupaten Lumajang');
insert into "cities" ("id", "province_id", "name") values (236, 15, 'Kabupaten Jember');
insert into "cities" ("id", "province_id", "name") values (237, 15, 'Kabupaten Banyuwangi');
insert into "cities" ("id", "province_id", "name") values (238, 15, 'Kabupaten Bondowoso');
insert into "cities" ("id", "province_id", "name") values (239, 15, 'Kabupaten Situbondo');
insert into "cities" ("id", "province_id", "name") values (240, 15, 'Kabupaten Probolinggo');
insert into "cities" ("id", "province_id", "name") values (241, 15, 'Kabupaten Pasuruan');
insert into "cities" ("id", "province_id", "name") values (242, 15, 'Kabupaten Sidoarjo');
insert into "cities" ("id", "province_id", "name") values (243, 15, 'Kabupaten Mojokerto');
insert into "cities" ("id", "province_id", "name") values (244, 15, 'Kabupaten Jombang');
insert into "cities" ("id", "province_id", "name") values (245, 15, 'Kabupaten Nganjuk');
insert into "cities" ("id", "province_id", "name") values (246, 15, 'Kabupaten Madiun');
insert into "cities" ("id", "province_id", "name") values (247, 15, 'Kabupaten Magetan');
insert into "cities" ("id", "province_id", "name") values (248, 15, 'Kabupaten Ngawi');
insert into "cities" ("id", "province_id", "name") values (249, 15, 'Kabupaten Bojonegoro');
insert into "cities" ("id", "province_id", "name") values (250, 15, 'Kabupaten Tuban');
insert into "cities" ("id", "province_id", "name") values (251, 15, 'Kabupaten Lamongan');
insert into "cities" ("id", "province_id", "name") values (252, 15, 'Kabupaten Gresik');
insert into "cities" ("id", "province_id", "name") values (253, 15, 'Kabupaten Bangkalan');
insert into "cities" ("id", "province_id", "name") values (254, 15, 'Kabupaten Sampang');
insert into "cities" ("id", "province_id", "name") values (255, 15, 'Kabupaten Pamekasan');
insert into "cities" ("id", "province_id", "name") values (256, 15, 'Kabupaten Sumenep');
insert into "cities" ("id", "province_id", "name") values (257, 15, 'Kota Kediri');
insert into "cities" ("id", "province_id", "name") values (258, 15, 'Kota Blitar');
insert into "cities" ("id", "province_id", "name") values (259, 15, 'Kota Malang');
insert into "cities" ("id", "province_id", "name") values (260, 15, 'Kota Probolinggo');
insert into "cities" ("id", "province_id", "name") values (261, 15, 'Kota Pasuruan');
insert into "cities" ("id", "province_id", "name") values (262, 15, 'Kota Mojokerto');
insert into "cities" ("id", "province_id", "name") values (263, 15, 'Kota Madiun');
insert into "cities" ("id", "province_id", "name") values (264, 15, 'Kota Surabaya');
insert into "cities" ("id", "province_id", "name") values (265, 15, 'Kota Batu');
insert into "cities" ("id", "province_id", "name") values (266, 16, 'Kabupaten Pandeglang');
insert into "cities" ("id", "province_id", "name") values (267, 16, 'Kabupaten Lebak');
insert into "cities" ("id", "province_id", "name") values (268, 16, 'Kabupaten Tangerang');
insert into "cities" ("id", "province_id", "name") values (269, 16, 'Kabupaten Serang');
insert into "cities" ("id", "province_id", "name") values (270, 16, 'Kota Tangerang');
insert into "cities" ("id", "province_id", "name") values (271, 16, 'Kota Cilegon');
insert into "cities" ("id", "province_id", "name") values (272, 16, 'Kota Serang');
insert into "cities" ("id", "province_id", "name") values (273, 16, 'Kota Tangerang Selatan');
insert into "cities" ("id", "province_id", "name") values (274, 17, 'Kabupaten Jembrana');
insert into "cities" ("id", "province_id", "name") values (275, 17, 'Kabupaten Tabanan');
insert into "cities" ("id", "province_id", "name") values (276, 17, 'Kabupaten Badung');
insert into "cities" ("id", "province_id", "name") values (277, 17, 'Kabupaten Gianyar');
insert into "cities" ("id", "province_id", "name") values (278, 17, 'Kabupaten Klungkung');
insert into "cities" ("id", "province_id", "name") values (279, 17, 'Kabupaten Bangli');
insert into "cities" ("id", "province_id", "name") values (280, 17, 'Kabupaten Karangasem');
insert into "cities" ("id", "province_id", "name") values (281, 17, 'Kabupaten Buleleng');
insert into "cities" ("id", "province_id", "name") values (282, 17, 'Kota Denpasar');
insert into "cities" ("id", "province_id", "name") values (283, 18, 'Kabupaten Lombok Barat');
insert into "cities" ("id", "province_id", "name") values (284, 18, 'Kabupaten Lombok Tengah');
insert into "cities" ("id", "province_id", "name") values (285, 18, 'Kabupaten Lombok Timur');
insert into "cities" ("id", "province_id", "name") values (286, 18, 'Kabupaten Sumbawa');
insert into "cities" ("id", "province_id", "name") values (287, 18, 'Kabupaten Dompu');
insert into "cities" ("id", "province_id", "name") values (288, 18, 'Kabupaten Bima');
insert into "cities" ("id", "province_id", "name") values (289, 18, 'Kabupaten Sumbawa Barat');
insert into "cities" ("id", "province_id", "name") values (290, 18, 'Kabupaten Lombok Utara');
insert into "cities" ("id", "province_id", "name") values (291, 18, 'Kota Mataram');
insert into "cities" ("id", "province_id", "name") values (292, 18, 'Kota Bima');
insert into "cities" ("id", "province_id", "name") values (293, 19, 'Kabupaten Kupang');
insert into "cities" ("id", "province_id", "name") values (294, 19, 'Kabupaten Timor Tengah Selatan');
insert into "cities" ("id", "province_id", "name") values (295, 19, 'Kabupaten Timor Tengah Utara');
insert into "cities" ("id", "province_id", "name") values (296, 19, 'Kabupaten Belu');
insert into "cities" ("id", "province_id", "name") values (297, 19, 'Kabupaten Alor');
insert into "cities" ("id", "province_id", "name") values (298, 19, 'Kabupaten Flores Timur');
insert into "cities" ("id", "province_id", "name") values (299, 19, 'Kabupaten Sikka');
insert into "cities" ("id", "province_id", "name") values (300, 19, 'Kabupaten Ende');
insert into "cities" ("id", "province_id", "name") values (301, 19, 'Kabupaten Ngada');
insert into "cities" ("id", "province_id", "name") values (302, 19, 'Kabupaten Manggarai');
insert into "cities" ("id", "province_id", "name") values (303, 19, 'Kabupaten Sumba Timur');
insert into "cities" ("id", "province_id", "name") values (304, 19, 'Kabupaten Sumba Barat');
insert into "cities" ("id", "province_id", "name") values (305, 19, 'Kabupaten Lembata');
insert into "cities" ("id", "province_id", "name") values (306, 19, 'Kabupaten Rote Ndao');
insert into "cities" ("id", "province_id", "name") values (307, 19, 'Kabupaten Manggarai Barat');
insert into "cities" ("id", "province_id", "name") values (308, 19, 'Kabupaten Nagekeo');
insert into "cities" ("id", "province_id", "name") values (309, 19, 'Kabupaten Sumba Tengah');
insert into "cities" ("id", "province_id", "name") values (310, 19, 'Kabupaten Sumba Barat Daya');
insert into "cities" ("id", "province_id", "name") values (311, 19, 'Kabupaten Manggarai Timur');
insert into "cities" ("id", "province_id", "name") values (312, 19, 'Kabupaten Sabu Raijua');
insert into "cities" ("id", "province_id", "name") values (313, 19, 'Kabupaten Malaka');
insert into "cities" ("id", "province_id", "name") values (314, 19, 'Kota Kupang');
insert into "cities" ("id", "province_id", "name") values (315, 20, 'Kabupaten Sambas');
insert into "cities" ("id", "province_id", "name") values (316, 20, 'Kabupaten Mempawah');
insert into "cities" ("id", "province_id", "name") values (317, 20, 'Kabupaten Sanggau');
insert into "cities" ("id", "province_id", "name") values (318, 20, 'Kabupaten Ketapang');
insert into "cities" ("id", "province_id", "name") values (319, 20, 'Kabupaten Sintang');
insert into "cities" ("id", "province_id", "name") values (320, 20, 'Kabupaten Kapuas Hulu');
insert into "cities" ("id", "province_id", "name") values (321, 20, 'Kabupaten Bengkayang');
insert into "cities" ("id", "province_id", "name") values (322, 20, 'Kabupaten Landak');
insert into "cities" ("id", "province_id", "name") values (323, 20, 'Kabupaten Sekadau');
insert into "cities" ("id", "province_id", "name") values (324, 20, 'Kabupaten Melawi');
insert into "cities" ("id", "province_id", "name") values (325, 20, 'Kabupaten Kayong Utara');
insert into "cities" ("id", "province_id", "name") values (326, 20, 'Kabupaten Kubu Raya');
insert into "cities" ("id", "province_id", "name") values (327, 20, 'Kota Pontianak');
insert into "cities" ("id", "province_id", "name") values (328, 20, 'Kota Singkawang');
insert into "cities" ("id", "province_id", "name") values (329, 21, 'Kabupaten Kotawaringin Barat');
insert into "cities" ("id", "province_id", "name") values (330, 21, 'Kabupaten Kotawaringin Timur');
insert into "cities" ("id", "province_id", "name") values (331, 21, 'Kabupaten Kapuas');
insert into "cities" ("id", "province_id", "name") values (332, 21, 'Kabupaten Barito Selatan');
insert into "cities" ("id", "province_id", "name") values (333, 21, 'Kabupaten Barito Utara');
insert into "cities" ("id", "province_id", "name") values (334, 21, 'Kabupaten Katingan');
insert into "cities" ("id", "province_id", "name") values (335, 21, 'Kabupaten Seruyan');
insert into "cities" ("id", "province_id", "name") values (336, 21, 'Kabupaten Sukamara');
insert into "cities" ("id", "province_id", "name") values (337, 21, 'Kabupaten Lamandau');
insert into "cities" ("id", "province_id", "name") values (338, 21, 'Kabupaten Gunung Mas');
insert into "cities" ("id", "province_id", "name") values (339, 21, 'Kabupaten Pulang Pisau');
insert into "cities" ("id", "province_id", "name") values (340, 21, 'Kabupaten Murung Raya');
insert into "cities" ("id", "province_id", "name") values (341, 21, 'Kabupaten Barito Timur');
insert into "cities" ("id", "province_id", "name") values (342, 21, 'Kota Palangkaraya');
insert into "cities" ("id", "province_id", "name") values (343, 22, 'Kabupaten Tanah Laut');
insert into "cities" ("id", "province_id", "name") values (344, 22, 'Kabupaten Kotabaru');
insert into "cities" ("id", "province_id", "name") values (345, 22, 'Kabupaten Banjar');
insert into "cities" ("id", "province_id", "name") values (346, 22, 'Kabupaten Barito Kuala');
insert into "cities" ("id", "province_id", "name") values (347, 22, 'Kabupaten Tapin');
insert into "cities" ("id", "province_id", "name") values (348, 22, 'Kabupaten Hulu Sungai Selatan');
insert into "cities" ("id", "province_id", "name") values (349, 22, 'Kabupaten Hulu Sungai Tengah');
insert into "cities" ("id", "province_id", "name") values (350, 22, 'Kabupaten Hulu Sungai Utara');
insert into "cities" ("id", "province_id", "name") values (351, 22, 'Kabupaten Tabalong');
insert into "cities" ("id", "province_id", "name") values (352, 22, 'Kabupaten Tanah Bumbu');
insert into "cities" ("id", "province_id", "name") values (353, 22, 'Kabupaten Balangan');
insert into "cities" ("id", "province_id", "name") values (354, 22, 'Kota Banjarmasin');
insert into "cities" ("id", "province_id", "name") values (355, 22, 'Kota Banjarbaru');
insert into "cities" ("id", "province_id", "name") values (356, 23, 'Kabupaten Paser');
insert into "cities" ("id", "province_id", "name") values (357, 23, 'Kabupaten Kutai Kartanegara');
insert into "cities" ("id", "province_id", "name") values (358, 23, 'Kabupaten Berau');
insert into "cities" ("id", "province_id", "name") values (359, 23, 'Kabupaten Kutai Barat');
insert into "cities" ("id", "province_id", "name") values (360, 23, 'Kabupaten Kutai Timur');
insert into "cities" ("id", "province_id", "name") values (361, 23, 'Kabupaten Penajam Paser Utara');
insert into "cities" ("id", "province_id", "name") values (362, 23, 'Kabupaten Mahakam Ulu');
insert into "cities" ("id", "province_id", "name") values (363, 23, 'Kota Balikpapan');
insert into "cities" ("id", "province_id", "name") values (364, 23, 'Kota Samarinda');
insert into "cities" ("id", "province_id", "name") values (365, 23, 'Kota Bontang');
insert into "cities" ("id", "province_id", "name") values (366, 24, 'Kabupaten Bulungan');
insert into "cities" ("id", "province_id", "name") values (367, 24, 'Kabupaten Malinau');
insert into "cities" ("id", "province_id", "name") values (368, 24, 'Kabupaten Nunukan');
insert into "cities" ("id", "province_id", "name") values (369, 24, 'Kabupaten Tana Tidung');
insert into "cities" ("id", "province_id", "name") values (370, 24, 'Kota Tarakan');
insert into "cities" ("id", "province_id", "name") values (371, 25, 'Kabupaten Bolaang Mongondow');
insert into "cities" ("id", "province_id", "name") values (372, 25, 'Kabupaten Minahasa');
insert into "cities" ("id", "province_id", "name") values (373, 25, 'Kabupaten Kepulauan Sangihe');
insert into "cities" ("id", "province_id", "name") values (374, 25, 'Kabupaten Kepulauan Talaud');
insert into "cities" ("id", "province_id", "name") values (375, 25, 'Kabupaten Minahasa Selatan');
insert into "cities" ("id", "province_id", "name") values (376, 25, 'Kabupaten Minahasa Utara');
insert into "cities" ("id", "province_id", "name") values (377, 25, 'Kabupaten Minahasa Tenggara');
insert into "cities" ("id", "province_id", "name") values (378, 25, 'Kabupaten Bolaang Mongondow Utara');
insert into "cities" ("id", "province_id", "name") values (379, 25, 'Kabupaten Kepulauan Siau Tagulandang Biaro (Sitaro)');
insert into "cities" ("id", "province_id", "name") values (380, 25, 'Kabupaten Bolaang Mongondow Timur');
insert into "cities" ("id", "province_id", "name") values (381, 25, 'Kabupaten Bolaang Mongondow Selatan');
insert into "cities" ("id", "province_id", "name") values (382, 25, 'Kota Manado');
insert into "cities" ("id", "province_id", "name") values (383, 25, 'Kota Bitung');
insert into "cities" ("id", "province_id", "name") values (384, 25, 'Kota Tomohon');
insert into "cities" ("id", "province_id", "name") values (385, 25, 'Kota Kotamobagu');
insert into "cities" ("id", "province_id", "name") values (386, 26, 'Kabupaten Banggai');
insert into "cities" ("id", "province_id", "name") values (387, 26, 'Kabupaten Poso');
insert into "cities" ("id", "province_id", "name") values (388, 26, 'Kabupaten Donggala');
insert into "cities" ("id", "province_id", "name") values (389, 26, 'Kabupaten Toli Toli');
insert into "cities" ("id", "province_id", "name") values (390, 26, 'Kabupaten Buol');
insert into "cities" ("id", "province_id", "name") values (391, 26, 'Kabupaten Morowali');
insert into "cities" ("id", "province_id", "name") values (392, 26, 'Kabupaten Banggai Kepulauan');
insert into "cities" ("id", "province_id", "name") values (393, 26, 'Kabupaten Parigi Moutong');
insert into "cities" ("id", "province_id", "name") values (394, 26, 'Kabupaten Tojo Una Una');
insert into "cities" ("id", "province_id", "name") values (395, 26, 'Kabupaten Sigi');
insert into "cities" ("id", "province_id", "name") values (396, 26, 'Kabupaten Banggai Laut');
insert into "cities" ("id", "province_id", "name") values (397, 26, 'Kabupaten Morowali Utara');
insert into "cities" ("id", "province_id", "name") values (398, 26, 'Kota Palu');
insert into "cities" ("id", "province_id", "name") values (399, 27, 'Kabupaten Kepulauan Selayar');
insert into "cities" ("id", "province_id", "name") values (400, 27, 'Kabupaten Bulukumba');
insert into "cities" ("id", "province_id", "name") values (401, 27, 'Kabupaten Bantaeng');
insert into "cities" ("id", "province_id", "name") values (402, 27, 'Kabupaten Jeneponto');
insert into "cities" ("id", "province_id", "name") values (403, 27, 'Kabupaten Takalar');
insert into "cities" ("id", "province_id", "name") values (404, 27, 'Kabupaten Gowa');
insert into "cities" ("id", "province_id", "name") values (405, 27, 'Kabupaten Sinjai');
insert into "cities" ("id", "province_id", "name") values (406, 27, 'Kabupaten Bone');
insert into "cities" ("id", "province_id", "name") values (407, 27, 'Kabupaten Maros');
insert into "cities" ("id", "province_id", "name") values (408, 27, 'Kabupaten Pangkajene Kepulauan');
insert into "cities" ("id", "province_id", "name") values (409, 27, 'Kabupaten Barru');
insert into "cities" ("id", "province_id", "name") values (410, 27, 'Kabupaten Soppeng');
insert into "cities" ("id", "province_id", "name") values (411, 27, 'Kabupaten Wajo');
insert into "cities" ("id", "province_id", "name") values (412, 27, 'Kabupaten Sidenreng Rappang');
insert into "cities" ("id", "province_id", "name") values (413, 27, 'Kabupaten Pinrang');
insert into "cities" ("id", "province_id", "name") values (414, 27, 'Kabupaten Enrekang');
insert into "cities" ("id", "province_id", "name") values (415, 27, 'Kabupaten Luwu');
insert into "cities" ("id", "province_id", "name") values (416, 27, 'Kabupaten Tana Toraja');
insert into "cities" ("id", "province_id", "name") values (417, 27, 'Kabupaten Luwu Utara');
insert into "cities" ("id", "province_id", "name") values (418, 27, 'Kabupaten Luwu Timur');
insert into "cities" ("id", "province_id", "name") values (419, 27, 'Kabupaten Toraja Utara');
insert into "cities" ("id", "province_id", "name") values (420, 27, 'Kota Makassar');
insert into "cities" ("id", "province_id", "name") values (421, 27, 'Kota Pare Pare');
insert into "cities" ("id", "province_id", "name") values (422, 27, 'Kota Palopo');
insert into "cities" ("id", "province_id", "name") values (423, 28, 'Kabupaten Kolaka');
insert into "cities" ("id", "province_id", "name") values (424, 28, 'Kabupaten Konawe');
insert into "cities" ("id", "province_id", "name") values (425, 28, 'Kabupaten Muna');
insert into "cities" ("id", "province_id", "name") values (426, 28, 'Kabupaten Buton');
insert into "cities" ("id", "province_id", "name") values (427, 28, 'Kabupaten Konawe Selatan');
insert into "cities" ("id", "province_id", "name") values (428, 28, 'Kabupaten Bombana');
insert into "cities" ("id", "province_id", "name") values (429, 28, 'Kabupaten Wakatobi');
insert into "cities" ("id", "province_id", "name") values (430, 28, 'Kabupaten Kolaka Utara');
insert into "cities" ("id", "province_id", "name") values (431, 28, 'Kabupaten Konawe Utara');
insert into "cities" ("id", "province_id", "name") values (432, 28, 'Kabupaten Buton Utara');
insert into "cities" ("id", "province_id", "name") values (433, 28, 'Kabupaten Kolaka Timur');
insert into "cities" ("id", "province_id", "name") values (434, 28, 'Kabupaten Konawe Kepulauan');
insert into "cities" ("id", "province_id", "name") values (435, 28, 'Kabupaten Muna Barat');
insert into "cities" ("id", "province_id", "name") values (436, 28, 'Kabupaten Buton Tengah');
insert into "cities" ("id", "province_id", "name") values (437, 28, 'Kabupaten Buton Selatan');
insert into "cities" ("id", "province_id", "name") values (438, 28, 'Kota Kendari');
insert into "cities" ("id", "province_id", "name") values (439, 28, 'Kota Bau Bau');
insert into "cities" ("id", "province_id", "name") values (440, 29, 'Kabupaten Gorontalo');
insert into "cities" ("id", "province_id", "name") values (441, 29, 'Kabupaten Boalemo');
insert into "cities" ("id", "province_id", "name") values (442, 29, 'Kabupaten Bone Bolango');
insert into "cities" ("id", "province_id", "name") values (443, 29, 'Kabupaten Pahuwato');
insert into "cities" ("id", "province_id", "name") values (444, 29, 'Kabupaten Gorontalo Utara');
insert into "cities" ("id", "province_id", "name") values (445, 29, 'Kota Gorontalo');
insert into "cities" ("id", "province_id", "name") values (446, 30, 'Kabupaten Pasangkayu (Mamuju Utara)');
insert into "cities" ("id", "province_id", "name") values (447, 30, 'Kabupaten Mamuju');
insert into "cities" ("id", "province_id", "name") values (448, 30, 'Kabupaten Mamasa');
insert into "cities" ("id", "province_id", "name") values (449, 30, 'Kabupaten Polewali Mandar');
insert into "cities" ("id", "province_id", "name") values (450, 30, 'Kabupaten Majene');
insert into "cities" ("id", "province_id", "name") values (451, 30, 'Kabupaten Mamuju Tengah');
insert into "cities" ("id", "province_id", "name") values (452, 31, 'Kabupaten Maluku Tengah');
insert into "cities" ("id", "province_id", "name") values (453, 31, 'Kabupaten Maluku Tenggara');
insert into "cities" ("id", "province_id", "name") values (454, 31, 'Kabupaten Kepulauan Tanimbar (Maluku Tenggara Barat)');
insert into "cities" ("id", "province_id", "name") values (455, 31, 'Kabupaten Buru');
insert into "cities" ("id", "province_id", "name") values (456, 31, 'Kabupaten Seram Bagian Timur');
insert into "cities" ("id", "province_id", "name") values (457, 31, 'Kabupaten Seram Bagian Barat');
insert into "cities" ("id", "province_id", "name") values (458, 31, 'Kabupaten Kepulauan Aru');
insert into "cities" ("id", "province_id", "name") values (459, 31, 'Kabupaten Maluku Barat Daya');
insert into "cities" ("id", "province_id", "name") values (460, 31, 'Kabupaten Buru Selatan');
insert into "cities" ("id", "province_id", "name") values (461, 31, 'Kota Ambon');
insert into "cities" ("id", "province_id", "name") values (462, 31, 'Kota Tual');
insert into "cities" ("id", "province_id", "name") values (463, 32, 'Kabupaten Halmahera Barat');
insert into "cities" ("id", "province_id", "name") values (464, 32, 'Kabupaten Halmahera Tengah');
insert into "cities" ("id", "province_id", "name") values (465, 32, 'Kabupaten Halmahera Utara');
insert into "cities" ("id", "province_id", "name") values (466, 32, 'Kabupaten Halmahera Selatan');
insert into "cities" ("id", "province_id", "name") values (467, 32, 'Kabupaten Kepulauan Sula');
insert into "cities" ("id", "province_id", "name") values (468, 32, 'Kabupaten Halmahera Timur');
insert into "cities" ("id", "province_id", "name") values (469, 32, 'Kabupaten Pulau Morotai');
insert into "cities" ("id", "province_id", "name") values (470, 32, 'Kabupaten Pulau Taliabu');
insert into "cities" ("id", "province_id", "name") values (471, 32, 'Kota Ternate');
insert into "cities" ("id", "province_id", "name") values (472, 32, 'Kota Tidore Kepulauan');
insert into "cities" ("id", "province_id", "name") values (473, 33, 'Kabupaten Jayapura');
insert into "cities" ("id", "province_id", "name") values (474, 33, 'Kabupaten Kepulauan Yapen');
insert into "cities" ("id", "province_id", "name") values (475, 33, 'Kabupaten Biak Numfor');
insert into "cities" ("id", "province_id", "name") values (476, 33, 'Kabupaten Sarmi');
insert into "cities" ("id", "province_id", "name") values (477, 33, 'Kabupaten Keerom');
insert into "cities" ("id", "province_id", "name") values (478, 33, 'Kabupaten Waropen');
insert into "cities" ("id", "province_id", "name") values (479, 33, 'Kabupaten Supiori');
insert into "cities" ("id", "province_id", "name") values (480, 33, 'Kabupaten Mamberamo Raya');
insert into "cities" ("id", "province_id", "name") values (481, 33, 'Kota Jayapura');
insert into "cities" ("id", "province_id", "name") values (482, 34, 'Kabupaten Sorong');
insert into "cities" ("id", "province_id", "name") values (483, 35, 'Kabupaten Manokwari');
insert into "cities" ("id", "province_id", "name") values (484, 35, 'Kabupaten Fak Fak');
insert into "cities" ("id", "province_id", "name") values (485, 34, 'Kabupaten Sorong Selatan');
insert into "cities" ("id", "province_id", "name") values (486, 34, 'Kabupaten Raja Ampat');
insert into "cities" ("id", "province_id", "name") values (487, 35, 'Kabupaten Teluk Bintuni');
insert into "cities" ("id", "province_id", "name") values (488, 35, 'Kabupaten Teluk Wondama');
insert into "cities" ("id", "province_id", "name") values (489, 35, 'Kabupaten Kaimana');
insert into "cities" ("id", "province_id", "name") values (490, 34, 'Kabupaten Tambrauw');
insert into "cities" ("id", "province_id", "name") values (491, 34, 'Kabupaten Maybrat');
insert into "cities" ("id", "province_id", "name") values (492, 35, 'Kabupaten Manokwari Selatan');
insert into "cities" ("id", "province_id", "name") values (493, 35, 'Kabupaten Pegunungan Arfak');
insert into "cities" ("id", "province_id", "name") values (494, 34, 'Kota Sorong');
insert into "cities" ("id", "province_id", "name") values (495, 36, 'Kabupaten Merauke');
insert into "cities" ("id", "province_id", "name") values (496, 36, 'Kabupaten Boven Digoel');
insert into "cities" ("id", "province_id", "name") values (497, 36, 'Kabupaten Mappi');
insert into "cities" ("id", "province_id", "name") values (498, 36, 'Kabupaten Asmat');
insert into "cities" ("id", "province_id", "name") values (499, 37, 'Kabupaten Nabire');
insert into "cities" ("id", "province_id", "name") values (500, 37, 'Kabupaten Puncak Jaya');
insert into "cities" ("id", "province_id", "name") values (501, 37, 'Kabupaten Paniai');
insert into "cities" ("id", "province_id", "name") values (502, 37, 'Kabupaten Mimika');
insert into "cities" ("id", "province_id", "name") values (503, 37, 'Kabupaten Puncak');
insert into "cities" ("id", "province_id", "name") values (504, 37, 'Kabupaten Dogiyai');
insert into "cities" ("id", "province_id", "name") values (505, 37, 'Kabupaten Intan Jaya');
insert into "cities" ("id", "province_id", "name") values (506, 37, 'Kabupaten Deiyai');
insert into "cities" ("id", "province_id", "name") values (507, 38, 'Kabupaten Jayawijaya');
insert into "cities" ("id", "province_id", "name") values (508, 38, 'Kabupaten Pegunungan Bintang');
insert into "cities" ("id", "province_id", "name") values (509, 38, 'Kabupaten Yahukimo');
insert into "cities" ("id", "province_id", "name") values (510, 38, 'Kabupaten Tolikara');
insert into "cities" ("id", "province_id", "name") values (511, 38, 'Kabupaten Mamberamo Tengah');
insert into "cities" ("id", "province_id", "name") values (512, 38, 'Kabupaten Yalimo');
insert into "cities" ("id", "province_id", "name") values (513, 38, 'Kabupaten Lanny Jaya');
insert into "cities" ("id", "province_id", "name") values (514, 38, 'Kabupaten Nduga');
