insert into "provinces" ("id", "name") values (1, 'Aceh (NAD)');
insert into "provinces" ("id", "name") values (2, 'Sumatera Utara');
insert into "provinces" ("id", "name") values (3, 'Sumatera Barat');
insert into "provinces" ("id", "name") values (4, 'Riau');
insert into "provinces" ("id", "name") values (5, 'Jambi');
insert into "provinces" ("id", "name") values (6, 'Sumatera Selatan');
insert into "provinces" ("id", "name") values (7, 'Bengkulu');
insert into "provinces" ("id", "name") values (8, 'Lampung');
insert into "provinces" ("id", "name") values (9, 'Kepulauan Bangka Belitung');
insert into "provinces" ("id", "name") values (10, 'Kepulauan Riau');
insert into "provinces" ("id", "name") values (11, 'DKI Jakarta');
insert into "provinces" ("id", "name") values (12, 'Jawa Barat');
insert into "provinces" ("id", "name") values (13, 'Jawa Tengah');
insert into "provinces" ("id", "name") values (14, 'DI Yogyakarta');
insert into "provinces" ("id", "name") values (15, 'Jawa Timur');
insert into "provinces" ("id", "name") values (16, 'Banten');
insert into "provinces" ("id", "name") values (17, 'Bali');
insert into "provinces" ("id", "name") values (18, 'Nusa Tenggara Barat (NTB)');
insert into "provinces" ("id", "name") values (19, 'Nusa Tenggara Timur (NTT)');
insert into "provinces" ("id", "name") values (20, 'Kalimantan Barat');
insert into "provinces" ("id", "name") values (21, 'Kalimantan Tengah');
insert into "provinces" ("id", "name") values (22, 'Kalimantan Selatan');
insert into "provinces" ("id", "name") values (23, 'Kalimantan Timur');
insert into "provinces" ("id", "name") values (24, 'Kalimantan Utara');
insert into "provinces" ("id", "name") values (25, 'Sulawesi Utara');
insert into "provinces" ("id", "name") values (26, 'Sulawesi Tengah');
insert into "provinces" ("id", "name") values (27, 'Sulawesi Selatan');
insert into "provinces" ("id", "name") values (28, 'Sulawesi Tenggara');
insert into "provinces" ("id", "name") values (29, 'Gorontalo');
insert into "provinces" ("id", "name") values (30, 'Sulawesi Barat');
insert into "provinces" ("id", "name") values (31, 'Maluku');
insert into "provinces" ("id", "name") values (32, 'Maluku Utara');
insert into "provinces" ("id", "name") values (33, 'Papua');
insert into "provinces" ("id", "name") values (34, 'Papua Barat Daya');
insert into "provinces" ("id", "name") values (35, 'Papua Barat');
insert into "provinces" ("id", "name") values (36, 'Papua Selatan');
insert into "provinces" ("id", "name") values (37, 'Papua Tengah');
insert into "provinces" ("id", "name") values (38, 'Papua Pegunungan');
